### ISSUE TITLE
scheduler-actor-reminders-client app crashing

### ISSUE THREAD

**Issue by elena-kolevska** [dapr/test-infra#240]
scheduler-actor-reminders-client app crashing: 

```
dapr client initializing for: 127.0.0.1:50001
2024/11/25 12:23:20 error starting health increase reminder: error invoking register actor reminder playerActorType/player-1: rpc error: code = PermissionDenied desc = operations on actor reminders are only possible on hosted actor types
2024/11/25 12:23:20 Started healthReminder for actor: player-1
2024/11/25 12:23:20 failed to start health decay reminder: %!w(*fmt.wrapError=&{error invoking register actor reminder playerActorType/player-1: rpc error: code = PermissionDenied desc = operations on actor reminders are only possible on hosted actor types 0xc0000ba048})
2024/11/25 12:23:25 error invoking actor method GetUser: error invoking binding playerActorType/player-1: rpc error: code = Internal desc = error invoke actor method: context deadline exceeded
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8f1a09]

goroutine 15 [running]:
main.monitorPlayerHealth({0xaf2180, 0xc00012a5a0}, {0xafdcc0, 0xc000070960}, {0xa1af0b, 0x8}, 0xc00007f110)
	/client/client/player-actor-client.go:181 +0x389
created by main.main in goroutine 1
	/client/client/player-actor-client.go:32 +0x185
```

**Comment by cicoyle** [comment]
This is really interesting this happens in CI. It runs perfectly fine on my laptop. Not sure of the diff btw envs

**Comment by elena-kolevska** [comment]
Fixed in https://github.com/dapr/test-infra/pull/241 and  https://github.com/dapr/test-infra/pull/243
